name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Store SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ls -lah key.pem  # ✅ Debug: Check if key.pem exists
          cat key.pem | head -n 5  # ✅ Debug: Show first 5 lines of key


      - name: Debug Key Header
        run: |
          head -n 1 key.pem

      - name: SSH into AWS and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: key.pem
          script: |
            cd /home/ec2-user/bbc_bot
            git pull origin main
            pm2 restart all


env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
