name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Debugging
        run: set -x  # Enables detailed output

      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into AWS and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ec2-user/bbc_bot
            git pull origin main
            pm2 restart all

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
